[package]
name = "common"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
diesel.workspace = true
ft-sdk.workspace = true
http.workspace = true
cookie.workspace = true
